FROM ubuntu:latest

RUN apt-get update -qq && apt-get install -y -qq bash jq openssl

WORKDIR /yana
COPY *.sh .
# COPY *.json .
COPY examples/linux ./example

RUN ./yana-test.sh

# ENTRYPOINT ["bash", "./yana.sh"]
