FROM  mcr.microsoft.com/windows/servercore:ltsc2025

WORKDIR /yana
COPY *.ps1 ./
# COPY *.json ./
# COPY examples ./examples/
COPY examples/windows ./example/

RUN powershell -File ./yana-test.ps1

# ENTRYPOINT ["powershell", "-File", "./yana.ps1"]
ENTRYPOINT ["powershell"]
