title: YANA - Yet Another Node Automator
description: A lightweight Configuration Management and Automation Tool for PowerShell and Bash
remote_theme: just-the-docs/just-the-docs
url: https://oops-42.github.io/yana

nav_sort: order

plugins:
  - jekyll-remote-theme

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.16.0"
