on:
  push:
    tags: ["v*.*.*"]
jobs:
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: true
          fail_on_unmatched_files: false
          generate_release_notes: true
          files: |
            yana_tests.sh
            yana_tests.ps1
